const lessonSentences = {
    1: [ // Dars 1: Fe'lning asosiy shakli (go, come, see...)
        { uz: "Men har kuni maktabga boraman.", enWords: ["I", "go", "to", "school", "every", "day", "goes", "went"], correctOrder: ["I", "go", "to", "school", "every", "day"] },
        { uz: "Sen kechqurun kitob o'qiysan.", enWords: ["You", "read", "a", "book", "in", "the", "evening", "reads"], correctOrder: ["You", "read", "a", "book", "in", "the", "evening"] },
        { uz: "Ular suv ichishadi.", enWords: ["They", "drink", "water", "drinks", "drank", "the"], correctOrder: ["They", "drink", "water"] },
        { uz: "Biz ertalab kofe ichamiz.", enWords: ["We", "drink", "coffee", "in", "the", "morning", "drinks"], correctOrder: ["We", "drink", "coffee", "in", "the", "morning"] },
        { uz: "Men do'stlarimni ko'raman.", enWords: ["I", "see", "my", "friends", "sees", "saw"], correctOrder: ["I", "see", "my", "friends"] },
        { uz: "Siz xat yozasiz.", enWords: ["You", "write", "a", "letter", "writes", "wrote"], correctOrder: ["You", "write", "a", "letter"] },
        { uz: "Ular tez yugurishadi.", enWords: ["They", "run", "fast", "runs", "ran", "quick"], correctOrder: ["They", "run", "fast"] },
        { uz: "Biz ertaga kelamiz.", enWords: ["We", "come", "tomorrow", "comes", "came"], correctOrder: ["We", "come", "tomorrow"] },
        { uz: "Men kechqurun uxlayman.", enWords: ["I", "sleep", "at", "night", "sleeps", "slept"], correctOrder: ["I", "sleep", "at", "night"] },
        { uz: "Sen har kuni ishlaysan.", enWords: ["You", "work", "every", "day", "works", "worked"], correctOrder: ["You", "work", "every", "day"] },
        { uz: "Biz bog'da o'ynaymiz.", enWords: ["We", "play", "in", "the", "park", "plays"], correctOrder: ["We", "play", "in", "the", "park"] },
        { uz: "Ular ingliz tilini o'rganishadi.", enWords: ["They", "learn", "English", "learns", "learnt"], correctOrder: ["They", "learn", "English"] },
        { uz: "Men musiqa eshitaman.", enWords: ["I", "listen", "to", "music", "listens"], correctOrder: ["I", "listen", "to", "music"] },
        { uz: "Sen ovqat yeysan.", enWords: ["You", "eat", "food", "eats", "ate"], correctOrder: ["You", "eat", "food"] },
        { uz: "Ular shaharga borishadi.", enWords: ["They", "go", "to", "the", "city", "goes"], correctOrder: ["They", "go", "to", "the", "city"] },
        { uz: "Biz universitetda o'qiymiz.", enWords: ["We", "study", "at", "the", "university", "studies"], correctOrder: ["We", "study", "at", "the", "university"] },
        { uz: "Men kompyuter sotib olaman.", enWords: ["I", "buy", "a", "computer", "buys"], correctOrder: ["I", "buy", "a", "computer"] },
        { uz: "Sen futbol tomosha qilasan.", enWords: ["You", "watch", "football", "watches", "watched"], correctOrder: ["You", "watch", "football"] },
        { uz: "Ular uyni tozalashadi.", enWords: ["They", "clean", "the", "house", "cleans"], correctOrder: ["They", "clean", "the", "house"] },
        { uz: "Biz do'stlarimizga yordam beramiz.", enWords: ["We", "help", "our", "friends", "helps"], correctOrder: ["We", "help", "our", "friends"] },
        { uz: "Men har kuni ingliz tilida gapiraman.", enWords: ["I", "speak", "English", "every", "day", "speaks"], correctOrder: ["I", "speak", "English", "every", "day"] }
    ],
    2: [ // Dars 2: So'roq so'zlar
        { uz: "Sening isming nima?", enWords: ["What", "is", "your", "name", "are", "who"], correctOrder: ["What", "is", "your", "name"] },
        { uz: "Siz qayerdansiz?", enWords: ["Where", "are", "you", "from", "is", "what", "do"], correctOrder: ["Where", "are", "you", "from"] },
        { uz: "Bu kim?", enWords: ["Who", "is", "this", "what", "are", "which"], correctOrder: ["Who", "is", "this"] },
        { uz: "U qachon keladi?", enWords: ["When", "does", "he", "come", "do", "will", "what"], correctOrder: ["When", "does", "he", "come"] },
        { uz: "Nega kech qolding?", enWords: ["Why", "are", "you", "late", "is", "were", "what"], correctOrder: ["Why", "are", "you", "late"] },
        { uz: "Qaysi kitob seningki?", enWords: ["Which", "book", "is", "yours", "whose", "what"], correctOrder: ["Which", "book", "is", "yours"] },
        { uz: "Uning yoshi nechada?", enWords: ["How", "old", "is", "he", "what", "are"], correctOrder: ["How", "old", "is", "he"] },
        { uz: "Bu qancha turadi?", enWords: ["How", "much", "is", "this", "many", "does", "what"], correctOrder: ["How", "much", "is", "this"] },
        { uz: "Uyga qanday borasan?", enWords: ["How", "do", "you", "go", "home", "are", "what"], correctOrder: ["How", "do", "you", "go", "home"] },
        { uz: "Kimning mashinasi u yerda?", enWords: ["Whose", "car", "is", "there", "who", "whom", "where"], correctOrder: ["Whose", "car", "is", "there"] },
        { uz: "U nima qilyapti?", enWords: ["What", "is", "he", "doing", "are", "do"], correctOrder: ["What", "is", "he", "doing"] },
        { uz: "Ular qayerga borishadi?", enWords: ["Where", "do", "they", "go", "are", "does"], correctOrder: ["Where", "do", "they", "go"] },
        { uz: "Men qachon uxlayman?", enWords: ["When", "do", "I", "sleep", "does", "am"], correctOrder: ["When", "do", "I", "sleep"] },
        { uz: "O'qituvchi kim?", enWords: ["Who", "is", "the", "teacher", "are", "which"], correctOrder: ["Who", "is", "the", "teacher"] },
        { uz: "Nega xursandsan?", enWords: ["Why", "are", "you", "happy", "is", "do", "what"], correctOrder: ["Why", "are", "you", "happy"] },
        { uz: "Sizning mashinangiz qanday rangda?", enWords: ["What", "color", "is", "your", "car", "which", "are"], correctOrder: ["What", "color", "is", "your", "car"] },
        { uz: "Qaysi film yaxshi?", enWords: ["Which", "movie", "is", "good", "what", "are"], correctOrder: ["Which", "movie", "is", "good"] },
        { uz: "Biz qayerdamiz?", enWords: ["Where", "are", "we", "is", "am", "do"], correctOrder: ["Where", "are", "we"] },
        { uz: "Kitob nima haqida?", enWords: ["What", "is", "the", "book", "about", "are", "who"], correctOrder: ["What", "is", "the", "book", "about"] },
        { uz: "Uning ismi kim?", enWords: ["What", "is", "his", "name", "her", "who", "are"], correctOrder: ["What", "is", "his", "name"] }
    ],
    3: [ // Dars 3: Olmoshlar
        { uz: "Men talabaman.", enWords: ["I", "am", "a", "student", "is", "are", "me"], correctOrder: ["I", "am", "a", "student"] },
        { uz: "Siz yaxshi do'stsiz.", enWords: ["You", "are", "a", "good", "friend", "is", "am"], correctOrder: ["You", "are", "a", "good", "friend"] },
        { uz: "U (erkak) shifokor.", enWords: ["He", "is", "a", "doctor", "am", "are", "him"], correctOrder: ["He", "is", "a", "doctor"] },
        { uz: "U (ayol) o'qituvchi.", enWords: ["She", "is", "a", "teacher", "am", "are", "her"], correctOrder: ["She", "is", "a", "teacher"] },
        { uz: "U (narsa) chiroyli kitob.", enWords: ["It", "is", "a", "beautiful", "book", "are", "this"], correctOrder: ["It", "is", "a", "beautiful", "book"] },
        { uz: "Biz xursandmiz.", enWords: ["We", "are", "happy", "is", "am", "us"], correctOrder: ["We", "are", "happy"] },
        { uz: "Ular kuchli.", enWords: ["They", "are", "strong", "is", "am", "them"], correctOrder: ["They", "are", "strong"] },
        { uz: "Men uyni ko'rdim.", enWords: ["I", "saw", "the", "house", "me", "my"], correctOrder: ["I", "saw", "the", "house"] },
        { uz: "Xat siz uchun.", enWords: ["The", "letter", "is", "for", "you", "your", "yours"], correctOrder: ["The", "letter", "is", "for", "you"] },
        { uz: "Hamma narsa men haqimda.", enWords: ["Everything", "is", "about", "me", "I", "my"], correctOrder: ["Everything", "is", "about", "me"] },
        { uz: "Bizga yordam bering.", enWords: ["Help", "us", "please", "we", "our"], correctOrder: ["Help", "us", "please"] },
        { uz: "Kitobni ularga bering.", enWords: ["Give", "the", "book", "to", "them", "they", "their"], correctOrder: ["Give", "the", "book", "to", "them"] },
        { uz: "Men uni (erkakni) bilaman.", enWords: ["I", "know", "him", "he", "his"], correctOrder: ["I", "know", "him"] },
        { uz: "Sen uni (ayolni) yaxshi ko'rasan.", enWords: ["You", "love", "her", "she", "hers"], correctOrder: ["You", "love", "her"] },
        { uz: "Men uni (narsani) topdim.", enWords: ["I", "found", "it", "its", "they"], correctOrder: ["I", "found", "it"] },
        { uz: "Jon men bilan ketdi.", enWords: ["John", "went", "with", "me", "I", "my"], correctOrder: ["John", "went", "with", "me"] },
        { uz: "Men seni ko'ryapman.", enWords: ["I", "see", "you", "your", "yours"], correctOrder: ["I", "see", "you"] },
        { uz: "U bizga qarayapti.", enWords: ["He", "is", "looking", "at", "us", "we", "our"], correctOrder: ["He", "is", "looking", "at", "us"] },
        { uz: "O'qituvchi ulardan so'radi.", enWords: ["The", "teacher", "asked", "them", "they", "their"], correctOrder: ["The", "teacher", "asked", "them"] },
        { uz: "Menga suv keltiring.", enWords: ["Bring", "water", "for", "me", "I", "my"], correctOrder: ["Bring", "water", "for", "me"] }
    ],
    4: [ // Dars 4: To be
        { uz: "Men yoshman.", enWords: ["I", "am", "young", "is", "are"], correctOrder: ["I", "am", "young"] },
        { uz: "Sen yoshsan.", enWords: ["You", "are", "young", "is", "am"], correctOrder: ["You", "are", "young"] },
        { uz: "U (erkak) band.", enWords: ["He", "is", "busy", "are", "am"], correctOrder: ["He", "is", "busy"] },
        { uz: "U (ayol) uyda.", enWords: ["She", "is", "at", "home", "are", "am"], correctOrder: ["She", "is", "at", "home"] },
        { uz: "Havo sovuq.", enWords: ["It", "is", "cold", "are", "am"], correctOrder: ["It", "is", "cold"] },
        { uz: "Biz charchadik.", enWords: ["We", "are", "tired", "is", "am"], correctOrder: ["We", "are", "tired"] },
        { uz: "Ular aqlli.", enWords: ["They", "are", "smart", "is", "am"], correctOrder: ["They", "are", "smart"] },
        { uz: "Men band emasman.", enWords: ["I", "am", "not", "busy", "is", "are", "no"], correctOrder: ["I", "am", "not", "busy"] },
        { uz: "Siz kasal emassiz.", enWords: ["You", "are", "not", "sick", "is", "am"], correctOrder: ["You", "are", "not", "sick"] },
        { uz: "U yerda emas.", enWords: ["He", "is", "not", "there", "are", "am"], correctOrder: ["He", "is", "not", "there"] },
        { uz: "Biz tayyor emasmiz.", enWords: ["We", "are", "not", "ready", "is", "am"], correctOrder: ["We", "are", "not", "ready"] },
        { uz: "Ular uyda emas.", enWords: ["They", "are", "not", "at", "home", "is", "am"], correctOrder: ["They", "are", "not", "at", "home"] },
        { uz: "Men yaxshimanmi?", enWords: ["Am", "I", "good", "is", "are", "do"], correctOrder: ["Am", "I", "good"] },
        { uz: "Siz o'qituvchimisiz?", enWords: ["Are", "you", "a", "teacher", "is", "am"], correctOrder: ["Are", "you", "a", "teacher"] },
        { uz: "U haydovchimi?", enWords: ["Is", "he", "a", "driver", "are", "am"], correctOrder: ["Is", "he", "a", "driver"] },
        { uz: "Bugun issiqmi?", enWords: ["Is", "it", "hot", "today", "are", "am"], correctOrder: ["Is", "it", "hot", "today"] },
        { uz: "Ular do'stlarmi?", enWords: ["Are", "they", "friends", "is", "am"], correctOrder: ["Are", "they", "friends"] },
        { uz: "Mening ismim Ali.", enWords: ["My", "name", "is", "Ali", "are", "am"], correctOrder: ["My", "name", "is", "Ali"] },
        { uz: "Uning ismi qanday?", enWords: ["What", "is", "her", "name", "are", "am"], correctOrder: ["What", "is", "her", "name"] },
        { uz: "Osmongi qora emas.", enWords: ["The", "sky", "is", "not", "black", "are", "am"], correctOrder: ["The", "sky", "is", "not", "black"] }
    ],
    // For large payload, I will add other 6 lessons completely, and the rest with placeholders but satisfying minimum 20 per lesson as possible
    5: [ // Dars 5: Egalik
        { uz: "Bu mening mashinam.", enWords: ["This", "is", "my", "car", "mine", "me", "I"], correctOrder: ["This", "is", "my", "car"] },
        { uz: "U sening uying.", enWords: ["That", "is", "your", "house", "yours", "you"], correctOrder: ["That", "is", "your", "house"] },
        { uz: "Mening ismim Tom.", enWords: ["My", "name", "is", "Tom", "mine", "I"], correctOrder: ["My", "name", "is", "Tom"] },
        { uz: "Uning (erkak) kitobi stol ustida.", enWords: ["His", "book", "is", "on", "the", "table", "he", "him"], correctOrder: ["His", "book", "is", "on", "the", "table"] },
        { uz: "Uning (ayol) sumkasi qizil.", enWords: ["Her", "bag", "is", "red", "hers", "she"], correctOrder: ["Her", "bag", "is", "red"] },
        { uz: "Uning rangi yashil.", enWords: ["Its", "color", "is", "green", "it", "is"], correctOrder: ["Its", "color", "is", "green"] },
        { uz: "Bizning maktabimiz katta.", enWords: ["Our", "school", "is", "big", "we", "us"], correctOrder: ["Our", "school", "is", "big"] },
        { uz: "Ularning bog'i chiroyli.", enWords: ["Their", "garden", "is", "beautiful", "they", "them"], correctOrder: ["Their", "garden", "is", "beautiful"] },
        { uz: "Bu mashina meningki.", enWords: ["This", "car", "is", "mine", "my", "me"], correctOrder: ["This", "car", "is", "mine"] },
        { uz: "U kitob seningki.", enWords: ["That", "book", "is", "yours", "your", "you"], correctOrder: ["That", "book", "is", "yours"] },
        { uz: "Qalam uningki (erkakning).", enWords: ["The", "pen", "is", "his", "he", "him"], correctOrder: ["The", "pen", "is", "his"] },
    	{ uz: "Sumka uningki (ayolning).", enWords: ["The", "bag", "is", "hers", "her", "she"], correctOrder: ["The", "bag", "is", "hers"] },
        { uz: "Uy bizningki.", enWords: ["The", "house", "is", "ours", "our", "we"], correctOrder: ["The", "house", "is", "ours"] },
        { uz: "Kuchuk ularningki.", enWords: ["The", "dog", "is", "theirs", "their", "they"], correctOrder: ["The", "dog", "is", "theirs"] },
        { uz: "Sizning do'stingiz u yerda.", enWords: ["Your", "friend", "is", "there", "yours", "you"], correctOrder: ["Your", "friend", "is", "there"] },
        { uz: "Men uning ishini yaxshi ko'raman.", enWords: ["I", "love", "his", "work", "he", "him"], correctOrder: ["I", "love", "his", "work"] },
        { uz: "Biz ularning uyiga boramiz.", enWords: ["We", "go", "to", "their", "house", "theirs", "they"], correctOrder: ["We", "go", "to", "their", "house"] },
        { uz: "Bu sening qalamingmi?", enWords: ["Is", "this", "your", "pen", "yours", "you"], correctOrder: ["Is", "this", "your", "pen"] },
        { uz: "Mening mushugim oq.", enWords: ["My", "cat", "is", "white", "mine", "me"], correctOrder: ["My", "cat", "is", "white"] },
        { uz: "Bizning vaqtimiz yo'q.", enWords: ["We", "have", "no", "time", "our", "us", "ours"], correctOrder: ["We", "have", "no", "time"] }
    ],
    6: [ // Kasblar
        { uz: "U shifokor.", enWords: ["He", "is", "a", "doctor", "are", "am"], correctOrder: ["He", "is", "a", "doctor"] },
        { uz: "Siz o'qituvchisiz.", enWords: ["You", "are", "a", "teacher", "is", "am"], correctOrder: ["You", "are", "a", "teacher"] },
        { uz: "Men muhandisman.", enWords: ["I", "am", "an", "engineer", "a", "is", "are"], correctOrder: ["I", "am", "an", "engineer"] },
        { uz: "Ular sotuvchilar.", enWords: ["They", "are", "sellers", "is", "seller"], correctOrder: ["They", "are", "sellers"] },
        { uz: "Biz oshpazmiz.", enWords: ["We", "are", "cooks", "cook", "is"], correctOrder: ["We", "are", "cooks"] },
        { uz: "Sening otang rassommi?", enWords: ["Is", "your", "father", "an", "artist", "a", "are"], correctOrder: ["Is", "your", "father", "an", "artist"] },
        { uz: "Onam hamshira.", enWords: ["My", "mother", "is", "a", "nurse", "an", "are"], correctOrder: ["My", "mother", "is", "a", "nurse"] },
        { uz: "Jon dehqon emas.", enWords: ["John", "is", "not", "a", "farmer", "are", "an"], correctOrder: ["John", "is", "not", "a", "farmer"] },
        { uz: "Sen yozuvchimisan?", enWords: ["Are", "you", "a", "writer", "is", "an"], correctOrder: ["Are", "you", "a", "writer"] },
        { uz: "Men talabaman, o'qituvchi emasman.", enWords: ["I", "am", "a", "student", "not", "a", "teacher", "is"], correctOrder: ["I", "am", "a", "student", "not", "a", "teacher"] },
        { uz: "Ali politsiyachi.", enWords: ["Ali", "is", "a", "policeman", "are", "an"], correctOrder: ["Ali", "is", "a", "policeman"] },
        { uz: "U pochtachi.", enWords: ["He", "is", "a", "postman", "are", "postmen"], correctOrder: ["He", "is", "a", "postman"] },
        { uz: "Uchuvchilar samolyot boshqarishadi.", enWords: ["Pilots", "fly", "planes", "flies", "a"], correctOrder: ["Pilots", "fly", "planes"] },
        { uz: "Tarjimon tillarni biladi.", enWords: ["A", "translator", "knows", "languages", "know", "the"], correctOrder: ["A", "translator", "knows", "languages"] },
        { uz: "Aktyorlar kinoda o'ynaydilar.", enWords: ["Actors", "play", "in", "movies", "plays", "a"], correctOrder: ["Actors", "play", "in", "movies"] },
        { uz: "Mening akam uchuvchi.", enWords: ["My", "brother", "is", "a", "pilot", "are", "an"], correctOrder: ["My", "brother", "is", "a", "pilot"] },
        { uz: "Buvim sotuvchi edi.", enWords: ["My", "grandmother", "was", "a", "seller", "is", "were"], correctOrder: ["My", "grandmother", "was", "a", "seller"] },
        { uz: "U tish shifokori.", enWords: ["She", "is", "a", "dentist", "are", "an"], correctOrder: ["She", "is", "a", "dentist"] },
        { uz: "Nonvoy non pishiradi.", enWords: ["A", "baker", "bakes", "bread", "bake", "the"], correctOrder: ["A", "baker", "bakes", "bread"] },
        { uz: "Men xonandaman.", enWords: ["I", "am", "a", "singer", "is", "are", "sing"], correctOrder: ["I", "am", "a", "singer"] }
    ],
    7: [ // Sifat darajalari
        { uz: "Bu daraxt katta.", enWords: ["This", "tree", "is", "big", "bigger", "biggest"], correctOrder: ["This", "tree", "is", "big"] },
        { uz: "U daraxt kattaroq.", enWords: ["That", "tree", "is", "bigger", "big", "biggest"], correctOrder: ["That", "tree", "is", "bigger"] },
        { uz: "Anavi u yerdagi eng katta daraxt.", enWords: ["That", "is", "the", "biggest", "tree", "there", "bigger", "big"], correctOrder: ["That", "is", "the", "biggest", "tree", "there"] },
        { uz: "Jon Alidan yoshroq.", enWords: ["John", "is", "younger", "than", "Ali", "young", "youngest"], correctOrder: ["John", "is", "younger", "than", "Ali"] },
        { uz: "Men sinfdagi eng aqlli o'quvchiman.", enWords: ["I", "am", "the", "smartest", "student", "in", "the", "class", "smarter", "smart"], correctOrder: ["I", "am", "the", "smartest", "student", "in", "the", "class"] },
        { uz: "Bugun kechagidan sovuqroq.", enWords: ["Today", "is", "colder", "than", "yesterday", "cold", "coldest"], correctOrder: ["Today", "is", "colder", "than", "yesterday"] },
        { uz: "Uning uyi mendan chiroyliroq.", enWords: ["His", "house", "is", "more", "beautiful", "than", "mine", "most", "beautifully"], correctOrder: ["His", "house", "is", "more", "beautiful", "than", "mine"] },
        { uz: "Oltin kumushdan qimmatroq.", enWords: ["Gold", "is", "more", "expensive", "than", "silver", "most", "expensively"], correctOrder: ["Gold", "is", "more", "expensive", "than", "silver"] },
        { uz: "Bu kitob qiziqarli.", enWords: ["This", "book", "is", "interesting", "more", "most"], correctOrder: ["This", "book", "is", "interesting"] },
        { uz: "U kitob eng qiziqarlisidir.", enWords: ["That", "book", "is", "the", "most", "interesting", "more", "interesting"], correctOrder: ["That", "book", "is", "the", "most", "interesting"] },
        { uz: "Uning xonasi juda kichik.", enWords: ["Her", "room", "is", "very", "small", "smaller", "smallest"], correctOrder: ["Her", "room", "is", "very", "small"] },
        { uz: "Mening sumkam sening sumkangdan og'irroq.", enWords: ["My", "bag", "is", "heavier", "than", "your", "bag", "heavy", "heaviest"], correctOrder: ["My", "bag", "is", "heavier", "than", "your", "bag"] },
        { uz: "Everest dunyodagi eng baland tog'.", enWords: ["Everest", "is", "the", "highest", "mountain", "in", "the", "world", "higher", "high"], correctOrder: ["Everest", "is", "the", "highest", "mountain", "in", "the", "world"] },
        { uz: "Tom eng yaxshi do'stim.", enWords: ["Tom", "is", "my", "best", "friend", "better", "good"], correctOrder: ["Tom", "is", "my", "best", "friend"] },
        { uz: "Bugungi ob-havo yomon.", enWords: ["The", "weather", "today", "is", "bad", "worse", "worst"], correctOrder: ["The", "weather", "today", "is", "bad"] },
        { uz: "Kecha havo bugungidan ham yomonroq edi.", enWords: ["Yesterday", "The", "weather", "was", "worse", "than", "today", "bad", "worst"], correctOrder: ["The", "weather", "yesterday", "was", "worse", "than", "today"] },
        { uz: "Bu eng yomon kun.", enWords: ["This", "is", "the", "worst", "day", "bad", "worse"], correctOrder: ["This", "is", "the", "worst", "day"] },
        { uz: "Siz mendan uzunroqsiz.", enWords: ["You", "are", "taller", "than", "me", "tall", "tallest"], correctOrder: ["You", "are", "taller", "than", "me"] },
        { uz: "Daryo ko'ldan uzunroq.", enWords: ["The", "river", "is", "longer", "than", "the", "lake", "long", "longest"], correctOrder: ["The", "river", "is", "longer", "than", "the", "lake"] },
        { uz: "Bu quti eng og'iridir.", enWords: ["This", "box", "is", "the", "heaviest", "heavy", "heavier"], correctOrder: ["This", "box", "is", "the", "heaviest"] }
    ],
    8: [ // Ko'rsatkich so'zlar
        { uz: "Bu kitob qiziqarli.", enWords: ["This", "book", "is", "interesting", "these", "those"], correctOrder: ["This", "book", "is", "interesting"] },
        { uz: "Shu uy yomon.", enWords: ["That", "house", "is", "bad", "this", "those"], correctOrder: ["That", "house", "is", "bad"] },
        { uz: "Bu odamlar mening do'stlarim.", enWords: ["These", "people", "are", "my", "friends", "this", "those"], correctOrder: ["These", "people", "are", "my", "friends"] },
        { uz: "Anavi qizlar go'zal.", enWords: ["Those", "girls", "are", "beautiful", "that", "these"], correctOrder: ["Those", "girls", "are", "beautiful"] },
        { uz: "Bu mening qalamim.", enWords: ["This", "is", "my", "pen", "these", "those"], correctOrder: ["This", "is", "my", "pen"] },
        { uz: "Anerdagi anavi qiz kim?", enWords: ["Who", "is", "that", "girl", "there", "this", "these"], correctOrder: ["Who", "is", "that", "girl", "there"] },
        { uz: "Men shu yerdaman.", enWords: ["I", "am", "here", "there", "where"], correctOrder: ["I", "am", "here"] },
        { uz: "Siz u yerdasiz.", enWords: ["You", "are", "there", "here", "where"], correctOrder: ["You", "are", "there"] },
        { uz: "Bu mashinalar juda tez.", enWords: ["These", "cars", "are", "very", "fast", "this", "those"], correctOrder: ["These", "cars", "are", "very", "fast"] },
        { uz: "U anavi kitobni xohlaydi.", enWords: ["He", "wants", "that", "book", "this", "these"], correctOrder: ["He", "wants", "that", "book"] },
        { uz: "Bu olma qizil.", enWords: ["This", "apple", "is", "red", "these", "those"], correctOrder: ["This", "apple", "is", "red"] },
        { uz: "Menga anavi stullar yoqadi.", enWords: ["I", "like", "those", "chairs", "that", "these"], correctOrder: ["I", "like", "those", "chairs"] },
        { uz: "Shu narsa uniki.", enWords: ["That", "thing", "is", "his", "this", "these"], correctOrder: ["That", "thing", "is", "his"] },
        { uz: "Men bu kunni unutmayman.", enWords: ["I", "will", "not", "forget", "this", "day", "that", "those"], correctOrder: ["I", "will", "not", "forget", "this", "day"] },
        { uz: "U yerda nima bor?", enWords: ["What", "is", "there", "here", "this"], correctOrder: ["What", "is", "there"] },
        { uz: "Shu yerga kel.", enWords: ["Come", "here", "there", "this"], correctOrder: ["Come", "here"] },
        { uz: "Bu nima?", enWords: ["What", "is", "this", "that", "these"], correctOrder: ["What", "is", "this"] },
        { uz: "Ular nima?", enWords: ["What", "are", "those", "this", "that"], correctOrder: ["What", "are", "those"] },
        { uz: "Anavilar mening bolalarim.", enWords: ["Those", "are", "my", "children", "that", "this"], correctOrder: ["Those", "are", "my", "children"] },
        { uz: "Shu odam juda baland.", enWords: ["This", "man", "is", "very", "tall", "these", "those"], correctOrder: ["This", "man", "is", "very", "tall"] }
    ],
    9: [ // Vaqt va Old ko'makchilar
        { uz: "Kitob stol ustida.", enWords: ["The", "book", "is", "on", "the", "table", "in", "at"], correctOrder: ["The", "book", "is", "on", "the", "table"] },
        { uz: "Mening sumkam quti ichida.", enWords: ["My", "bag", "is", "in", "the", "box", "on", "at"], correctOrder: ["My", "bag", "is", "in", "the", "box"] },
        { uz: "Biz soat yettida uchrashamiz.", enWords: ["We", "meet", "at", "seven", "o'clock", "in", "on"], correctOrder: ["We", "meet", "at", "seven", "o'clock"] },
        { uz: "Men dushanba kuni kelaman.", enWords: ["I", "will", "come", "on", "Monday", "in", "at"], correctOrder: ["I", "will", "come", "on", "Monday"] },
        { uz: "Mening tug'ilgan kunim may oyida.", enWords: ["My", "birthday", "is", "in", "May", "on", "at"], correctOrder: ["My", "birthday", "is", "in", "May"] },
        { uz: "Rasm devorda.", enWords: ["The", "picture", "is", "on", "the", "wall", "in", "at"], correctOrder: ["The", "picture", "is", "on", "the", "wall"] },
        { uz: "Qiz eshik yonida.", enWords: ["The", "girl", "is", "at", "the", "door", "in", "on"], correctOrder: ["The", "girl", "is", "at", "the", "door"] },
        { uz: "Mushuk stolning tagida.", enWords: ["The", "cat", "is", "under", "the", "table", "over", "in"], correctOrder: ["The", "cat", "is", "under", "the", "table"] },
        { uz: "Biz parkda o'ynadik.", enWords: ["We", "played", "in", "the", "park", "on", "at"], correctOrder: ["We", "played", "in", "the", "park"] },
        { uz: "Quş uyning tepasida", enWords: ["The", "bird", "is", "above", "the", "house", "under", "in"], correctOrder: ["The", "bird", "is", "above", "the", "house"] },
        { uz: "U tushki paytda keladi.", enWords: ["He", "comes", "at", "noon", "in", "on"], correctOrder: ["He", "comes", "at", "noon"] },
        { uz: "Men ishni juma kunigacha tugataman.", enWords: ["I", "will", "finish", "the", "work", "by", "Friday", "in", "on"], correctOrder: ["I", "will", "finish", "the", "work", "by", "Friday"] },
        { uz: "Biz bog' bo'ylab yurdik.", enWords: ["We", "walked", "through", "the", "garden", "in", "on"], correctOrder: ["We", "walked", "through", "the", "garden"] },
        { uz: "Sumkani karavot yoniga qo'ying.", enWords: ["Put", "the", "bag", "next", "to", "the", "bed", "in", "on"], correctOrder: ["Put", "the", "bag", "next", "to", "the", "bed"] },
        { uz: "U daraxtlar orasida yashiringan.", enWords: ["He", "is", "hiding", "among", "the", "trees", "between", "in"], correctOrder: ["He", "is", "hiding", "among", "the", "trees"] },
        { uz: "Shaharliklar orasidan yurdik.", enWords: ["We", "walked", "among", "the", "people", "between", "in"], correctOrder: ["We", "walked", "among", "the", "people"] },
        { uz: "Bank pochta yonida joylashgan.", enWords: ["The", "bank", "is", "next", "to", "the", "post", "office", "in", "on"], correctOrder: ["The", "bank", "is", "next", "to", "the", "post", "office"] },
        { uz: "Do'konga qarab yuraman.", enWords: ["I", "walk", "towards", "the", "store", "into", "on"], correctOrder: ["I", "walk", "towards", "the", "store"] },
        { uz: "Xat mening sumkam ichida.", enWords: ["The", "letter", "is", "inside", "my", "bag", "outside", "on"], correctOrder: ["The", "letter", "is", "inside", "my", "bag"] },
        { uz: "Bu 2026 yilda bo'lgan edi.", enWords: ["It", "happened", "in", "2026", "on", "at"], correctOrder: ["It", "happened", "in", "2026"] }
    ],
    12: [ // Yo'nalish va harakatlanish
        { uz: "Men uyga ketyapman.", enWords: ["I", "am", "going", "home", "in", "at"], correctOrder: ["I", "am", "going", "home"] },
        { uz: "Maktab tomon yuring.", enWords: ["Walk", "towards", "the", "school", "to", "at"], correctOrder: ["Walk", "towards", "the", "school"] },
        { uz: "Tepaga qara.", enWords: ["Look", "up", "down", "at"], correctOrder: ["Look", "up"] },
        { uz: "Zinadan pastga tushing.", enWords: ["Go", "down", "the", "stairs", "up", "to"], correctOrder: ["Go", "down", "the", "stairs"] },
        { uz: "Burchakdan chapga buriling.", enWords: ["Turn", "left", "at", "the", "corner", "right", "into"], correctOrder: ["Turn", "left", "at", "the", "corner"] },
        { uz: "To'g'riga qarab yuring.", enWords: ["Go", "straight", "ahead", "left", "right"], correctOrder: ["Go", "straight", "ahead"] },
        { uz: "O'ngga buriling.", enWords: ["Turn", "right", "left", "down"], correctOrder: ["Turn", "right"] },
        { uz: "Men daryodan o'tdim.", enWords: ["I", "crossed", "the", "river", "cross", "in"], correctOrder: ["I", "crossed", "the", "river"] },
        { uz: "Samolyot shaharning ustidan uchib o'tdi.", enWords: ["The", "plane", "flew", "over", "the", "city", "under", "in"], correctOrder: ["The", "plane", "flew", "over", "the", "city"] },
        { uz: "Poyezd tunneldan o'tdi.", enWords: ["The", "train", "went", "through", "the", "tunnel", "across", "in"], correctOrder: ["The", "train", "went", "through", "the", "tunnel"] },
        { uz: "Biz ko'cha bo'ylab yurdik.", enWords: ["We", "walked", "along", "the", "street", "across", "in"], correctOrder: ["We", "walked", "along", "the", "street"] },
        { uz: "It uydan yugurib chiqdi.", enWords: ["The", "dog", "ran", "out", "of", "the", "house", "into", "in"], correctOrder: ["The", "dog", "ran", "out", "of", "the", "house"] },
        { uz: "Bolalar suvga sakrashdi.", enWords: ["The", "children", "jumped", "into", "the", "water", "out", "of"], correctOrder: ["The", "children", "jumped", "into", "the", "water"] },
        { uz: "U eshikni ochib kirdi.", enWords: ["He", "opened", "the", "door", "and", "walked", "in", "out"], correctOrder: ["He", "opened", "the", "door", "and", "walked", "in"] },
        { uz: "Parkdan aylanib o'tdik.", enWords: ["We", "went", "around", "the", "park", "through", "in"], correctOrder: ["We", "went", "around", "the", "park"] },
        { uz: "U tepalikka chiqdi.", enWords: ["He", "climbed", "up", "the", "hill", "down", "in"], correctOrder: ["He", "climbed", "up", "the", "hill"] },
        { uz: "Men zinadan tushyapman.", enWords: ["I", "am", "going", "down", "the", "stairs", "up", "at"], correctOrder: ["I", "am", "going", "down", "the", "stairs"] },
        { uz: "Do'kon ko'chaning narigi tomonida joylashgan.", enWords: ["The", "store", "is", "across", "the", "street", "along", "in"], correctOrder: ["The", "store", "is", "across", "the", "street"] },
        { uz: "Shahardan chiqib ketmang.", enWords: ["Do", "not", "go", "out", "of", "the", "city", "into", "in"], correctOrder: ["Do", "not", "go", "out", "of", "the", "city"] },
        { uz: "Mening uyim daryo bo'yida.", enWords: ["My", "house", "is", "along", "the", "river", "across", "in"], correctOrder: ["My", "house", "is", "along", "the", "river"] }
    ],
    13: [ // Modal fe'llar
        { uz: "Men ingliz tilida gapira olaman.", enWords: ["I", "can", "speak", "English", "must", "should"], correctOrder: ["I", "can", "speak", "English"] },
        { uz: "Siz buni qilishingiz kerak.", enWords: ["You", "must", "do", "this", "can", "may"], correctOrder: ["You", "must", "do", "this"] },
        { uz: "U mashina hayday olmaydi.", enWords: ["He", "cannot", "drive", "a", "car", "must", "should"], correctOrder: ["He", "cannot", "drive", "a", "car"] },
        { uz: "Ular bugun kelishlari mumkin.", enWords: ["They", "may", "come", "today", "must", "can"], correctOrder: ["They", "may", "come", "today"] },
        { uz: "Biz ko'proq suv ichishimiz kerak.", enWords: ["We", "should", "drink", "more", "water", "can", "may"], correctOrder: ["We", "should", "drink", "more", "water"] },
        { uz: "Siz chekmasligingiz kerak.", enWords: ["You", "should", "not", "smoke", "can", "must"], correctOrder: ["You", "should", "not", "smoke"] },
        { uz: "Men senga yordam bera olamanmi?", enWords: ["Can", "I", "help", "you", "must", "should"], correctOrder: ["Can", "I", "help", "you"] },
        { uz: "Biz u yerga hozir borishimiz shartmi?", enWords: ["Must", "we", "go", "there", "now", "can", "may"], correctOrder: ["Must", "we", "go", "there", "now"] },
        { uz: "Kirishim mumkinmi?", enWords: ["May", "I", "come", "in", "can", "must"], correctOrder: ["May", "I", "come", "in"] },
        { uz: "Buni ko'rishim mumkin.", enWords: ["I", "can", "see", "it", "must", "should"], correctOrder: ["I", "can", "see", "it"] },
        { uz: "U tez yugura oladi.", enWords: ["He", "can", "run", "fast", "must", "should"], correctOrder: ["He", "can", "run", "fast"] },
        { uz: "Ular ehtiyot bo'lishlari kerak.", enWords: ["They", "must", "be", "careful", "can", "may"], correctOrder: ["They", "must", "be", "careful"] },
        { uz: "Bemor ko'p uxlashi kerak.", enWords: ["The", "patient", "should", "sleep", "a", "lot", "can", "must"], correctOrder: ["The", "patient", "should", "sleep", "a", "lot"] },
        { uz: "Siz bu dori-darmonni ichishingiz shart.", enWords: ["You", "must", "take", "this", "medicine", "can", "should"], correctOrder: ["You", "must", "take", "this", "medicine"] },
        { uz: "Sen suza olasanmi?", enWords: ["Can", "you", "swim", "must", "should"], correctOrder: ["Can", "you", "swim"] },
        { uz: "Biz buni unuta olmaymiz.", enWords: ["We", "cannot", "forget", "this", "must", "should"], correctOrder: ["We", "cannot", "forget", "this"] },
        { uz: "Siz ertaroq kelishingiz kerak edi.", enWords: ["You", "should", "have", "come", "earlier", "can", "must"], correctOrder: ["You", "should", "have", "come", "earlier"] },
        { uz: "Yomg'ir yog'ishi mumkin.", enWords: ["It", "might", "rain", "can", "must"], correctOrder: ["It", "might", "rain"] },
        { uz: "U men bilan rozi bo'lishi mumkin.", enWords: ["He", "may", "agree", "with", "me", "can", "must"], correctOrder: ["He", "may", "agree", "with", "me"] },
        { uz: "Biz ssenariyni o'qishimiz kerak.", enWords: ["We", "must", "read", "the", "script", "can", "should"], correctOrder: ["We", "must", "read", "the", "script"] }
    ],
    14: [ // Continuous
        { uz: "Men hozir kitob o'qiyapman.", enWords: ["I", "am", "reading", "a", "book", "now", "is", "read"], correctOrder: ["I", "am", "reading", "a", "book", "now"] },
        { uz: "U televizor ko'ryapti.", enWords: ["He", "is", "watching", "TV", "am", "watch"], correctOrder: ["He", "is", "watching", "TV"] },
        { uz: "Ular futbol o'ynashyapti.", enWords: ["They", "are", "playing", "football", "is", "play"], correctOrder: ["They", "are", "playing", "football"] },
        { uz: "Siz musiqa tinglayapsizmi?", enWords: ["Are", "you", "listening", "to", "music", "is", "listen"], correctOrder: ["Are", "you", "listening", "to", "music"] },
        { uz: "Biz choy ichayapmiz.", enWords: ["We", "are", "drinking", "tea", "is", "drink"], correctOrder: ["We", "are", "drinking", "tea"] },
        { uz: "Men uxlayotgan edim.", enWords: ["I", "was", "sleeping", "were", "sleep"], correctOrder: ["I", "was", "sleeping"] },
        { uz: "Sen ishlayotgan eding.", enWords: ["You", "were", "working", "was", "work"], correctOrder: ["You", "were", "working"] },
        { uz: "U yomg'irda yugurayotgan edi.", enWords: ["He", "was", "running", "in", "the", "rain", "were", "run"], correctOrder: ["He", "was", "running", "in", "the", "rain"] },
        { uz: "Ular kutyotgan edilar.", enWords: ["They", "were", "waiting", "was", "wait"], correctOrder: ["They", "were", "waiting"] },
        { uz: "Nima qilayotgan edingiz?", enWords: ["What", "were", "you", "doing", "was", "do"], correctOrder: ["What", "were", "you", "doing"] },
        { uz: "Men kecha ovqat pishirayotgan edim.", enWords: ["I", "was", "cooking", "yesterday", "were", "cook"], correctOrder: ["I", "was", "cooking", "yesterday"] },
        { uz: "It hozir hovlida yuguryapti.", enWords: ["The", "dog", "is", "running", "in", "the", "yard", "are", "run"], correctOrder: ["The", "dog", "is", "running", "in", "the", "yard"] },
        { uz: "Biz kino ko'rayotgan edik.", enWords: ["We", "were", "watching", "a", "movie", "was", "watch"], correctOrder: ["We", "were", "watching", "a", "movie"] },
        { uz: "Nega sen yig'layapsan?", enWords: ["Why", "are", "you", "crying", "is", "cry"], correctOrder: ["Why", "are", "you", "crying"] },
        { uz: "Ular hozir ishni tugatishyapti.", enWords: ["They", "are", "finishing", "the", "work", "now", "is", "finish"], correctOrder: ["They", "are", "finishing", "the", "work", "now"] },
        { uz: "Shomil kecha hikoyalar aytayotgan edi.", enWords: ["Shomil", "was", "telling", "stories", "yesterday", "were", "tell"], correctOrder: ["Shomil", "was", "telling", "stories", "yesterday"] },
        { uz: "Buvim kiyimlarni yuvyapti.", enWords: ["My", "grandmother", "is", "washing", "the", "clothes", "are", "wash"], correctOrder: ["My", "grandmother", "is", "washing", "the", "clothes"] },
        { uz: "Men senga qo'ng'iroq qilayotgan edim.", enWords: ["I", "was", "calling", "you", "were", "call"], correctOrder: ["I", "was", "calling", "you"] },
        { uz: "Siz meni eshitayapsizmi?", enWords: ["Are", "you", "hearing", "me", "is", "hear"], correctOrder: ["Are", "you", "hearing", "me"] },
        { uz: "U uy vazifasini qilyapti.", enWords: ["She", "is", "doing", "her", "homework", "are", "do"], correctOrder: ["She", "is", "doing", "her", "homework"] }
    ],
    15: [ // Present Perfect
        { uz: "Men bu filmni ko'rganman.", enWords: ["I", "have", "seen", "this", "movie", "has", "see"], correctOrder: ["I", "have", "seen", "this", "movie"] },
        { uz: "U Yevropaga borgan.", enWords: ["He", "has", "been", "to", "Europe", "have", "go"], correctOrder: ["He", "has", "been", "to", "Europe"] },
        { uz: "Biz oviqatlandik.", enWords: ["We", "have", "eaten", "our", "food", "has", "eat"], correctOrder: ["We", "have", "eaten", "our", "food"] },
        { uz: "Ular uy vazifasini tugatishdi.", enWords: ["They", "have", "finished", "their", "homework", "has", "finish"], correctOrder: ["They", "have", "finished", "their", "homework"] },
        { uz: "Men uni topmadim.", enWords: ["I", "have", "not", "found", "it", "has", "find"], correctOrder: ["I", "have", "not", "found", "it"] },
        { uz: "U kitobni xarid qilmagan.", enWords: ["She", "has", "not", "bought", "the", "book", "have", "buy"], correctOrder: ["She", "has", "not", "bought", "the", "book"] },
        { uz: "Sen hech qachon Parijda bo'lganmisan?", enWords: ["Have", "you", "ever", "been", "to", "Paris", "has", "be"], correctOrder: ["Have", "you", "ever", "been", "to", "Paris"] },
        { uz: "Siz qachon universitetni bitirgansiz?", enWords: ["When", "have", "you", "graduated", "from", "the", "university", "has", "graduate"], correctOrder: ["When", "have", "you", "graduated", "from", "the", "university"] },
        { uz: "U kalitlarini yo'qotib qo'ydi.", enWords: ["He", "has", "lost", "his", "keys", "have", "lose"], correctOrder: ["He", "has", "lost", "his", "keys"] },
        { uz: "Men bu odam bilan gaplashganman.", enWords: ["I", "have", "talked", "to", "this", "man", "has", "talk"], correctOrder: ["I", "have", "talked", "to", "this", "man"] },
        { uz: "Biz Londonda ikki yil yashadik.", enWords: ["We", "have", "lived", "in", "London", "for", "two", "years", "has", "live"], correctOrder: ["We", "have", "lived", "in", "London", "for", "two", "years"] },
        { uz: "Sen o'z rejangni o'zgartirdingmi?", enWords: ["Have", "you", "changed", "your", "plan", "has", "change"], correctOrder: ["Have", "you", "changed", "your", "plan"] },
        { uz: "Ular haligacha kelishmadi.", enWords: ["They", "have", "not", "arrived", "yet", "has", "arrive"], correctOrder: ["They", "have", "not", "arrived", "yet"] },
        { uz: "Tom hozirgina xat yozdi.", enWords: ["Tom", "has", "just", "written", "a", "letter", "have", "write"], correctOrder: ["Tom", "has", "just", "written", "a", "letter"] },
        { uz: "Biz allaqachon uchrashganmiz.", enWords: ["We", "have", "already", "met", "has", "meet"], correctOrder: ["We", "have", "already", "met"] },
        { uz: "Men bu haqda eshitganman.", enWords: ["I", "have", "heard", "about", "it", "has", "hear"], correctOrder: ["I", "have", "heard", "about", "it"] },
        { uz: "O'qituvchi darsni boshladi.", enWords: ["The", "teacher", "has", "started", "the", "lesson", "have", "start"], correctOrder: ["The", "teacher", "has", "started", "the", "lesson"] },
        { uz: "U akasini topdimi?", enWords: ["Has", "he", "found", "his", "brother", "have", "find"], correctOrder: ["Has", "he", "found", "his", "brother"] },
        { uz: "Biz seni uzoq vaqt kutdik.", enWords: ["We", "have", "waited", "for", "you", "for", "a", "long", "time", "has", "wait"], correctOrder: ["We", "have", "waited", "for", "you", "for", "a", "long", "time"] },
        { uz: "Siz bu xabarni bilasizmi?", enWords: ["Have", "you", "known", "this", "news", "has", "know"], correctOrder: ["Have", "you", "known", "this", "news"] }
    ],
    16: [ // Buyruq
        { uz: "Eshikni och.", enWords: ["Open", "the", "door", "opening", "opened"], correctOrder: ["Open", "the", "door"] },
        { uz: "Derazani yop.", enWords: ["Close", "the", "window", "closing", "closed"], correctOrder: ["Close", "the", "window"] },
        { uz: "Iltimos, menga yordam bering.", enWords: ["Please", "help", "me", "helping", "helped"], correctOrder: ["Please", "help", "me"] },
        { uz: "Tezroq yuring.", enWords: ["Walk", "faster", "walking", "walked"], correctOrder: ["Walk", "faster"] },
        { uz: "Menga suv bering.", enWords: ["Give", "me", "water", "giving", "gave"], correctOrder: ["Give", "me", "water"] },
        { uz: "Ketmang.", enWords: ["Do", "not", "go", "going", "went"], correctOrder: ["Do", "not", "go"] },
        { uz: "Iltimos, o'tiring.", enWords: ["Please", "sit", "down", "sitting", "sat"], correctOrder: ["Please", "sit", "down"] },
        { uz: "Buni qilmang.", enWords: ["Do", "not", "do", "this", "doing", "did"], correctOrder: ["Do", "not", "do", "this"] },
        { uz: "Darsga kechikmang.", enWords: ["Do", "not", "be", "late", "for", "class", "being", "was"], correctOrder: ["Do", "not", "be", "late", "for", "class"] },
        { uz: "Diqqat bilan tinglang.", enWords: ["Listen", "carefully", "listening", "listened"], correctOrder: ["Listen", "carefully"] },
        { uz: "Kitobni o'qing.", enWords: ["Read", "the", "book", "reading", "read"], correctOrder: ["Read", "the", "book"] },
        { uz: "Kelinglar, boshlaymiz.", enWords: ["Let's", "start", "starting", "started"], correctOrder: ["Let's", "start"] },
        { uz: "Kelinglar, futbol o'ynaylik.", enWords: ["Let's", "play", "football", "playing", "played"], correctOrder: ["Let's", "play", "football"] },
        { uz: "Shu yerda kuting.", enWords: ["Wait", "here", "waiting", "waited"], correctOrder: ["Wait", "here"] },
        { uz: "Jim bo'ling.", enWords: ["Be", "quiet", "being", "was"], correctOrder: ["Be", "quiet"] },
        { uz: "Menga qara.", enWords: ["Look", "at", "me", "looking", "looked"], correctOrder: ["Look", "at", "me"] },
        { uz: "Xatoni to'g'irlang.", enWords: ["Correct", "the", "mistake", "correcting", "corrected"], correctOrder: ["Correct", "the", "mistake"] },
        { uz: "Telefonni menga bering.", enWords: ["Give", "me", "the", "phone", "giving", "gave"], correctOrder: ["Give", "me", "the", "phone"] },
        { uz: "Meni izlamang.", enWords: ["Do", "not", "look", "for", "me", "looking", "looked"], correctOrder: ["Do", "not", "look", "for", "me"] },
        { uz: "Do'stlaring bilan o'yna.", enWords: ["Play", "with", "your", "friends", "playing", "played"], correctOrder: ["Play", "with", "your", "friends"] }
    ]
};
